### ISSUE TITLE
Font defaults to "Terminus (TTF):style=Bold"

### ISSUE THREAD

**Issue by acly7946** [milgra/sov#1]
I do not have this font installed, so the text is a bunch of boxes.

You could change the default to 'sans' or 'monospace' which are aliases to other fonts that should be present on any system. 'sans' on my system is an alias to 'Liberation Sans'.

From a brief glance src/sov/config/config.c needs to be changed.

If you're intending on making the config part of the code (like dwm/st), then perhaps it could output an error if the font can't be found.

**Comment by milgra** [comment]
Hi, If you want to customize the font just copy /usr/share/sov/config to ~/.config/sov/config and add your favorite font as font face. But you are right, I should use some generic font in the default config, thank you!

**Comment by acly7946** [comment]
Thanks for telling me. I completely forgot to look at sov -h.

**Comment by milgra** [comment]
No problem, thank you for using sov! :)
