### ISSUE TITLE
Add compilation flag to overwrite default `/etc` `/usr` paths

### ISSUE THREAD

**Issue by simoneruffini** [milgra/sov#19]
For distros like NixOS that "sandbox" applications it is helpful to be able to overwrite the default path where SOV will read default cofigurations or other hardcoded files. 
For now the problem is resolved via a patch applied before the buildling phase of the package (see patch of @TravisDavis-ops  [here](https://github.com/NixOS/nixpkgs/pull/178882/commits/e52b891189f631feb2f09de682e0ab23212a6034#diff-b14aa7f3f9e39732e2f4c0e3b068cd0e9c20cfa7f4d086a380a66575fa1d9effR17-R19) ) but this is not the best way of handling this in my opinion.   
Instead a solution like this [one](https://github.com/alex-courtis/way-displays/pull/48/commits/9ca4fe6e9ed4593b769426289dca08f66007703e) is more appropriate. 

I the next days I'll take a look at the repo to see if I can issue a PR but I never had experience with meson/ninja so I will not promise anything.

**Comment by eli-schwartz** [comment]
https://github.com/milgra/sov/blob/e57a84f367058024d36127f2e703da5e9489659d/src/sov/main.c#L36

The `/usr/share` should be replaced by a macro defined in meson.build as e.g.

```meson
add_project_arguments(
    '-DPACKAGE_DATADIR=' + join_paths(get_option('prefix'), get_option('datadir')),
    language: 'c',
)

**Comment by milgra** [comment]
Thanks, I will add it to the next version.

**Comment by milgra** [comment]
It's done in [0.72](https://github.com/milgra/sov/releases/tag/0.72)
