### ISSUE TITLE
Adding border color and radius

### ISSUE THREAD

**Issue by Heisfer** [milgra/sov#20]
I suggest adding 5 more config variables (if possible):
`window_border_radius` - change window border radius
`window_border_color` - change window border color
`window_border_sizer` - change window border thickness?
`border_radios` - for workspace border 
`border_size `- workspace border thickness

Adding those 5 would help people to style it more to their looks and feel with custom styles.

**Comment by milgra** [comment]
Hi, border color and radius is totally doable, I will look into the others, thanks for the suggestions!

**Comment by Slickytail** [comment]
Just submitted a pull request (#24) that implements `border_radius` configuration

**Comment by milgra** [comment]
Added in https://github.com/milgra/sov/releases/tag/0.74
