### ISSUE TITLE
Blurry font with scaled displays

### ISSUE THREAD

**Issue by zsolt-donca** [milgra/sov#23]
I just found `sov`. I love the idea :heart: , but when I gave it a try, found out that the text it shows is actually quite blurry:

![image](https://user-images.githubusercontent.com/6824167/188688062-8d6ee6c0-235c-457e-9e99-de0ba7666a49.png)

Above is a screenshot with crisp text from `foot` but blurry text from `sov`. The above screen is scaled with a scaling factor of 2. I also have another screen with a scaling factor of 1.5, in case that's relevant.

**Comment by milgra** [comment]
Hi, I never tried sov with scaling yet, that is the cause for sure, I will look into it, thanks!

**Comment by milgra** [comment]
Hi, it should work in the latest version.

**Comment by shaunsingh** [comment]
![20230308_17h46m11s_grim](https://user-images.githubusercontent.com/71196912/223868703-a290d384-9a12-4d0c-b972-4a9685744062.png)

Still appears blurry for me, running on sway with 2x scaling

**Comment by shaunsingh** [comment]
Sorry, nixOS packaged an older version of sov, newer version works

**Comment by milgra** [comment]
Cool, no problem.
