### ISSUE TITLE
Missing error checking in src/sov/config/fontconfig.c

### ISSUE THREAD

**Issue by emixa-d** [milgra/sov#26]
I noticed that in src/sov/config/fontconfig.c, 'popen' is called without checking for `NULL` (e.g. if fc-match was not in $PATH). For better error messages (instead of a crash because of a NULL, or maybe even silently continuing or corrupting memory on systems without memory protection), I recommend checking the return value.

**Comment by milgra** [comment]
Thank you very much for pointing that out, I will add a fix in the next version.

**Comment by milgra** [comment]
fixed in https://github.com/milgra/sov/releases/tag/0.74
