### ISSUE TITLE
[Feature Request] Show overview until release of $mod

### ISSUE THREAD

**Issue by humanplayer2** [milgra/sov#30]
I would love if Sway Overview could be set to 

1. show on `$mod+key` (as it is now),
2. remain shown when `key` is released, but `$mod` held,
3. refresh on workspace switching, and
4. hide when `$mod` is released.

I think this would both improve the experience of using Sway Overview when changing with `$mod+1-$mod+9` etc., where `$mod` could now be held while choosing what number to change to, and also when switching to next and previous workspaces.

I could imagine others would also be happy for this feature. @larskotthoff mentions [mentions it](https://github.com/swaywm/sway/pull/6920#issuecomment-1231981571), and it is an implemented feature of [Workspace Matrix](https://github.com/mzur/gnome-shell-wsmatrix) for Gnome where it makes maneuvering the space of workspaces a breeze.

It is my impression that the way keybindings are implemented in Sway makes it impossible to implement this through the Sway config alone. The patch from [this rejected PR](https://github.com/swaywm/sway/pull/6920) makes it possible, but changes `--release` a lot, which was [given as a reason for rejecting it](https://github.com/swaywm/sway/pull/6920#issuecomment-1291930024). Additionally, Sway Overview does not refresh when workspaces are switched if it remains shown.

Another reason given for the PR rejection is that the behavior should be implementable through current Wayland protocols for apps that use layer-shell---which I from the description guess Sway Overview does?

**Comment by milgra** [comment]
Hi, it's possible, I will look into it.

**Comment by milgra** [comment]
Hi, it's ready in v0.93. Took a year, sorry!
