### ISSUE TITLE
Clickable Workspaces + Auto-update while Shown [Feature Request]

### ISSUE THREAD

**Issue by hmpthcs** [milgra/sov#33]
Using SOV on a tablet would benefit greatly from allowing the user to move to a given workspace by tapping (clicking) on it. 

In addition, auto-updating a static SOV in sitting "show" mode could, along with the above feature, allow SOV to be used not just as a map of workspaces, but as a also as a great touchscreen/tablet navigation tool.  This could presumably be accomplished by listening to workspace / window events via the sway IPC socket.

**Comment by hmpthcs** [comment]
I've looked a bit into the sources both for SOV and your other project, WCP. Obviously, both use html + css for configuration of user interfaces using kineticUI. 

I am wondering if SOV would support clickable/tappable buttons in the same way that WCP does. Is it possible to simply modify the html file to implement the button idea? If not, would it be difficult to extend SOV to include the underlying framework that allows WCP to display buttons and respond to user input?

**Comment by milgra** [comment]
Hi, try v0.93, workspaces are now clickable.
