### ISSUE TITLE
[Feature Request] Add support to scroll through workspaces to display ones that exceed the screen

### ISSUE THREAD

**Issue by IceAsteroid** [milgra/sov#41]
I have a script [here](https://github.com/IceAsteroid/swayWorkroom.sh), as an extension to sway to have more than 10 workspaces.

Now, when I have a lot of workspaces opened, sov will display some workspaces exceeding on the screen.

Like the following:
![screenShot-grim_20230622164817](https://github.com/milgra/sov/assets/90975914/49ae10f6-5f47-4166-9edf-247cd39b58e3)
![screenShot-grim_20230622164633](https://github.com/milgra/sov/assets/90975914/30147c94-3a90-4956-b0cd-f68afc431eb0)

How can I see the rest of workspaces, without shrinking down sov to display on my screen?

Since I'm working on a small screen laptop, making it display smaller overally isn't really an option, as the text will be too small to see.

**Comment by IceAsteroid** [comment]
I know this looks bizarre, I don't need so many workspaces to open at the same time either. But just in case, is it worth the effort to implement it?

**Comment by milgra** [comment]
Hi! Well, that's super edge case! But the main problem is that I want to keep sov totally interactionless, it's just a passive layer that appears and disappears quickly so I won't add the feature.
