### ISSUE TITLE
Bug: CSS colors don't follow standard: #RRGGBBAA

### ISSUE THREAD

**Issue by trinitronx** [milgra/sov#42]
After trying to set colors for `sov` to match my desktop theme, I noticed that colors didn't seem to be displayed correctly.  Later, by experimenting with setting `FF` for each octet, [I discovered][1] that the format currently seems to be:

```
#BBGGRRAA
```

Since this Kinetic UI seems to be using CSS files for styling, it should probably be corrected to use the standard CSS format instead:

```
#RRGGBBAA
```

It might be that the color channels are flipped in endian-ness, or some other mistake was made to flip them when handling the hexidecimal color codes somewhere in the code.

[1]: https://github.com/milgra/sov/issues/40#issuecomment-1613850648

**Comment by milgra** [comment]
Thanks for the PR, I will look into it soon.
