### ISSUE TITLE
Workspacenumbers in the last column are missing

### ISSUE THREAD

**Issue by matthis-k** [milgra/sov#5]
![screenshot_2022-04-26_12-17-34_502020533](https://user-images.githubusercontent.com/69082876/165278566-00ccea4e-d2e4-410d-a39f-012a16ec9eae.png)

configuration: default one, only with the FiraCode Nerd Font

**Comment by milgra** [comment]
Wow, strange issue, I will look into it, thank you!

**Comment by milgra** [comment]
Hm, it's not font related, can you please insert/attach the results of
``
swaymsg -t get_tree | jq > tst_tree.json && swaymsg -t get_workspaces | jq > tst_ws.json
```
I can reproduce the issue with these two files.

**Comment by milgra** [comment]
It should be fixed in v0.7, please check if it works correctly.

**Comment by matthis-k** [comment]
Ok, i tried it again just now and it was all normal like intended (before the update)
