### ISSUE TITLE
Build fails with multiple errors

### ISSUE THREAD

**Issue by brihadeesh** [milgra/sov#8]
I've been trying to get this working on Void Linux both using xbps-src as well as directly running `meson build` and `ninja -C build` from a terminal and it fails during the second command (i.e. `ninja -C build`) with the error `ninja: build stopped: subcommand failed`

and with the following output: 

```
ninja: Entering directory `build'
[19/60] Compiling C object sov.p/src_sov_config_fontconfig.c.o
../src/sov/config/fontconfig.c: In function 'fontconfig_new_path':
../src/sov/config/fontconfig.c:22:19: warning: implicit declaration of function 'popen'; did you mean 'fopen'?  -Wimplicit-function-declaration]
   22 |   FILE* pipe    = popen(command, "r");                                    // CLOSE 0
      |                   ^~~~~
      |                   fopen
../src/sov/config/fontconfig.c:22:19: warning: initialization of 'FILE *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
../src/sov/config/fontconfig.c:26:3: warning: implicit declaration of function 'pclose'; did you mean 'fclose'? [-Wimplicit-function-declaration]
   26 |   pclose(pipe); // CLOSE 0
      |   ^~~~~~
      |   fclose
../src/sov/config/fontconfig.c:32:18: warning: initialization of 'FILE *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   32 |     FILE* pipe = popen(command, "r");                                   // CLOSE 1
      |                  ^~~~~
../src/sov/config/fontconfig.c:42:20: warning: initialization of 'FILE *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   42 |       FILE* pipe = popen(command, "r");                    // CLOSE 2
      |                    ^~~~~
[20/60] Compiling C object sov.p/src_modules_storage_kvlines.c.o
FAILED: sov.p/src_modules_storage_kvlines.c.o
cc -Isov.p -I. -I.. -I../src/sov/config -I../src/sov/tree -I../src/modules/json -I../src/modules/storage -I../src/modules/zen_core -I../src/modules/zen_text -I/usr/include/freetype2 -I/usr/include/libpng16 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O0 -g '-DSOV_VERSION="0.61"' -DDEBUG -MD -MQ sov.p/src_modules_storage_kvlines.c.o -MF sov.p/src_modules_storage_kvlines.c.o.d -o sov.p/src_modules_storage_kvlines.c.o -c ../src/modules/storage/kvlines.c
../src/modules/storage/kvlines.c: In function 'kvlines_write':
../src/modules/storage/kvlines.c:102:32: error: 'PATH_MAX' undeclared (first use in this function)
  102 |   char* path = cstr_new_format(PATH_MAX + NAME_MAX, "%snew", libpath); // REL 0
      |                                ^~~~~~~~
../src/modules/storage/kvlines.c:102:32: note: each undeclared identifier is reported only once for each function it appears in
../src/modules/storage/kvlines.c:102:43: error: 'NAME_MAX' undeclared (first use in this function)
  102 |   char* path = cstr_new_format(PATH_MAX + NAME_MAX, "%snew", libpath); // REL 0
      |                                           ^~~~~~~~
[25/60] Compiling C object sov.p/src_modules_zen_core_zc_bitmap.c.o
ninja: build stopped: subcommand failed.
```

Any help? I'm quite new to meson-style builds.

**Comment by milgra** [comment]
Can you please try https://github.com/milgra/sov/releases/tag/0.62 ? popen should be in stdio.h so I explicitly import it in every file where it is needed, I hope that it solves this problem.

**Comment by milgra** [comment]
for PATH_MAX errors please try to include <linux/limits.h> where <limits.h> is included, that should help, it seems that on void it's not in it's standard place.

**Comment by brihadeesh** [comment]
> Can you please try https://github.com/milgra/sov/releases/tag/0.62 ? popen should be in stdio.h so I explicitly import it in every file where it is needed, I hope that it solves this problem.

I did but it persists for fontconfig.c

**Comment by brihadeesh** [comment]
> for PATH_MAX errors please try to include <linux/limits.h> where <limits.h> is included, that should help, it seems that on void it's not in it's standard place.

I just checked with some of the package maintainers over at #xbps and they were fairly certain limits.h should work fine.

**Comment by putchar** [comment]
Hello
I am trying to package `sov` in nix and i am facing the same issue with the same error log

**Comment by brihadeesh** [comment]
Looks like there are some includes missing. It's definitely odd that the AUR package seems to be building fine.

**Comment by hissssst** [comment]
Experiencing exactly the same issue

**Comment by putchar** [comment]
doing this sed on the following files fixed it for me 
```
sed -i '/^#include <limits.h>/a#include <linux/limits.h>' \
      src/sov/main.c \
      src/sov/config/config.c \
      src/sov/tree_test.c \
      src/modules/zen_core/zc_cstrpath.c \
      src/modules/storage/kvlines.c
```

**Comment by milgra** [comment]
I don't want to use linux/limits.h but I can add "linux" as an include directory if exists, I will try it on ubuntu/void.

**Comment by brihadeesh** [comment]
@putchar does it run after the sed? Just tried with Void and sov segfaults if run.

**Comment by putchar** [comment]
> @putchar does it run after the sed? Just tried with Void and sov segfaults if run.

Hello
I am doing the sed during the packaging in nix (just before the build) https://gitlab.com/putchar/dotnix/-/blob/main/Home-Manager/modules/sway/sov.nix 
I can confirm sov works when i use it in nixos

**Comment by brihadeesh** [comment]
> I am doing the sed during the packaging in nix (just before the build) https://gitlab.com/putchar/dotnix/-/blob/main/Home-Manager/modules/sway/sov.nix

Same, I've added a patch that runs prior to packaging on Void.

**Comment by brihadeesh** [comment]
@milgra Two things I wanted to add:

1. Some people over at #xbps (IRC for Void Linux package maintainers) suggested **not** to use <linux/limits.h> as opposed to just <limits.h> although as I said before build and packaging runs fine when I do as you'd suggested earlier
2. On replacing <limits.h> with <linux/limits.h> and installing the package generated, sov seems to segfault with the following error

```
swayoverview v0.62 by Milan Toth ( www.milgra.com )
listens on standard input for '0' - hide panel '1' - show panel '2' - quit
1651475406.854064 DEBUG ../src/modules/zen_core/zc_log.c:145: Set log level to DEBUG
1651475406.854800 INFO  ../src/sov/main.c:737: Using config file : /usr/share/sov/config

Segmentation fault
```

Any suggestions?

**Comment by milgra** [comment]
Hi, I will install a void linux this week and figure this out.

**Comment by milgra** [comment]
Okay, please try the latest version ( 0.63 ), it worked for me on Void. There were two issues : on some linux distros the standard limits.h doesn't contain PATH_MAX and linux/limits.h - which is the part of the linux-headers package usually - contains it. The other thing is that GCC needs an exact _POSIX_C_SOURCE version definition to be able to compile pipe in stdio.h and CLANG - that I use - doesn't need it so I added it to the code. Hope it works.

**Comment by brihadeesh** [comment]
Great, this fixes it! Closing.
